packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

# Optional: Configure package resolution
catalog:
  react: ^18.2.0
  react-native: ^0.72.0
  typescript: ^5.0.0
  graphql: ^16.8.0
  apollo-server-express: ^3.12.0
  "@apollo/client": ^3.8.0